# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPk-iQBQdAnuV-ui2ejR67ua7Q_AVH62
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
import pandas as pd
import plotly.express as px

# Page configuration
st.set_page_config(page_title="E-commerce Dashboard", layout="wide")

# Title
st.title(" E-commerce Market Trend Analysis Dashboard")
st.markdown("### AI-Powered Insights for Indian E-commerce")
st.markdown("---")

# Load data
@st.cache_data
def load_data():
    listoforders_df = pd.read_csv("List of Orders.csv")
    orderdetails_df = pd.read_csv("Order Details.csv")
    data = pd.merge(listoforders_df, orderdetails_df, on='Order ID' ,how ='outer')
    data['Order Date'] = pd.to_datetime(data['Order Date'], format='%d-%m-%Y', errors='coerce')
    data['Month_Name'] = data['Order Date'].dt.month_name()
    data['Year'] = data['Order Date'].dt.year
    data['Quarter'] = data['Order Date'].dt.quarter
    data['Profit_Margin'] = (data['Profit'] / data['Amount']) * 100
    data['Is_Loss'] = data['Profit'] < 0
    return data

data = load_data()

# Sidebar filters
st.sidebar.header(" Filters")
st.sidebar.markdown("Select filters to customize your view")

categories = st.sidebar.multiselect(
    "Select Category:",
    options=data['Category'].unique(),
    default=data['Category'].unique()
)

states = st.sidebar.multiselect(
    "Select State:",
    options=data['State'].unique(),
    default=list(data['State'].unique())[:5]  # Default to top 5 states
)

# Filter data
filtered_data = data[
    (data['Category'].isin(categories)) &
    (data['State'].isin(states))
]

# Key Metrics Section
st.header("Key Performance Indicators")

col1, col2, col3, col4 = st.columns(4)

with col1:
    total_sales = filtered_data['Amount'].sum()
    st.metric("Total Sales", f"₹{total_sales:,.0f}", delta="Revenue")

with col2:
    total_profit = filtered_data['Profit'].sum()
    profit_margin = (total_profit / total_sales * 100) if total_sales > 0 else 0
    st.metric("Total Profit", f"₹{total_profit:,.0f}", delta=f"{profit_margin:.1f}% margin")

with col3:
    total_transactions = len(filtered_data)
    st.metric("Total Transactions", f"{total_transactions:,}")

with col4:
    loss_count = filtered_data['Is_Loss'].sum()
    loss_pct = (loss_count / len(filtered_data) * 100) if len(filtered_data) > 0 else 0
    st.metric("Loss Transactions", f"{loss_count}", delta=f"{loss_pct:.1f}%", delta_color="inverse")

st.markdown("---")

"""# New section"""

# Visualization Section 1: Sales Trends
st.header("Sales Performance Analysis")

col1, col2 = st.columns(2)

with col1:
    st.subheader(" Monthly Sales Trend")
    monthly_sales = filtered_data.groupby('Month_Name')['Amount'].sum().reset_index()

    # Order months properly
    month_order = ['January', 'February', 'March', 'April', 'May', 'June',
                   'July', 'August', 'September', 'October', 'November', 'December']
    available_months = [m for m in month_order if m in monthly_sales['Month_Name'].values]
    monthly_sales['Month_Name'] = pd.Categorical(monthly_sales['Month_Name'],
                                                   categories=available_months, ordered=True)
    monthly_sales = monthly_sales.sort_values('Month_Name')

    fig1 = px.line(monthly_sales, x='Month_Name', y='Amount',
                   labels={'Amount': 'Sales (₹)', 'Month_Name': 'Month'},
                   title='Sales Trend Over Time')
    fig1.update_traces(line_color='#2ecc71', line_width=3)
    fig1.update_layout(hovermode='x unified')
    st.plotly_chart(fig1, use_container_width=True)

with col2:
    st.subheader("🎯 Sales Distribution by Category")
    category_sales = filtered_data.groupby('Category')['Amount'].sum().reset_index()
    fig2 = px.pie(category_sales, values='Amount', names='Category',
                  title='Category-wise Sales Distribution',
                  color_discrete_sequence=px.colors.qualitative.Set3)
    st.plotly_chart(fig2, use_container_width=True)

st.markdown("---")

# Visualization Section 2: Product Analysis
st.header("💰 Product Performance Insights")

col3, col4 = st.columns(2)

with col3:
    st.subheader("Top 10 Products by Revenue")
    top_products = filtered_data.groupby('Sub-Category')['Amount'].sum().nlargest(10).reset_index()
    fig3 = px.bar(top_products, x='Amount', y='Sub-Category',
                  orientation='h',
                  labels={'Amount': 'Total Sales (₹)', 'Sub-Category': 'Product'},
                  title='Best Selling Products',
                  color='Amount',
                  color_continuous_scale='Blues')
    fig3.update_layout(showlegend=False)
    st.plotly_chart(fig3, use_container_width=True)

with col4:
    st.subheader("Profit vs Loss Products")
    product_profit = filtered_data.groupby('Sub-Category')['Profit'].sum().reset_index()
    product_profit = product_profit.sort_values('Profit')

    # Show top 5 profitable and top 5 loss-making
    top_profit = product_profit.tail(5)
    top_loss = product_profit.head(5)
    combined = pd.concat([top_loss, top_profit])

    fig4 = px.bar(combined, x='Profit', y='Sub-Category',
                  orientation='h',
                  labels={'Profit': 'Total Profit (₹)', 'Sub-Category': 'Product'},
                  title='Most Profitable vs Loss-Making Products',
                  color='Profit',
                  color_continuous_scale='RdYlGn')
    fig4.update_layout(showlegend=False)
    st.plotly_chart(fig4, use_container_width=True)

st.markdown("---")

# Visualization Section 3: Geographic Analysis
st.header(" Geographic Distribution")

col5, col6 = st.columns(2)

with col5:
    st.subheader("Top 10 States by Sales")
    state_sales = filtered_data.groupby('State')['Amount'].sum().nlargest(10).reset_index()
    fig5 = px.bar(state_sales, x='Amount', y='State',
                  orientation='h',
                  labels={'Amount': 'Total Sales (₹)', 'State': 'State'},
                  title='State-wise Sales Performance',
                  color='Amount',
                  color_continuous_scale='Reds')
    fig5.update_layout(showlegend=False)
    st.plotly_chart(fig5, use_container_width=True)

with col6:
    st.subheader("Customer Distribution by State")
    state_customers = filtered_data.groupby('State')['CustomerName'].nunique().nlargest(10).reset_index()
    state_customers.columns = ['State', 'Customer_Count']
    fig6 = px.bar(state_customers, x='Customer_Count', y='State',
                  orientation='h',
                  labels={'Customer_Count': 'Number of Customers', 'State': 'State'},
                  title='State-wise Customer Base',
                  color='Customer_Count',
                  color_continuous_scale='Purples')
    fig6.update_layout(showlegend=False)
    st.plotly_chart(fig6, use_container_width=True)

st.markdown("---")

# Data Table Section
st.header("Transaction Data Explorer")
st.subheader("Filtered Transaction Records")

# Show filtered data
display_cols = ['Order Date', 'CustomerName', 'State', 'City', 'Category',
                'Sub-Category', 'Amount', 'Profit', 'Quantity']
st.dataframe(filtered_data[display_cols].head(100), use_container_width=True)

# Download option
csv = filtered_data.to_csv(index=False)
st.download_button(
    label="📥 Download Filtered Data as CSV",
    data=csv,
    file_name="filtered_ecommerce_data.csv",
    mime="text/csv"
)

st.markdown("---")

# Footer
st.markdown("# Key Insights")
st.info("""
**Business Recommendations:**
- Focus on top-performing categories for marketing campaigns
- Address loss-making products through pricing or discontinuation strategies
- Target high-revenue states for expansion
- Monitor monthly trends for seasonal inventory planning
""")

st.caption("AI-Powered Market Trend Analysis Dashboard | IIT Ropar Minor in AI Project")